# Generated by Django 5.2 on 2025-04-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('trending_products', 'Trending products'), ('sold_out', 'Sold out'), ('comingsoon', 'Coming soon'), ('on_sale', 'On Sale'), ('new', 'New'), ('best_seler', 'Best seler')], default='active', max_length=20),
        ),
    ]
