# Generated by Django 5.2 on 2025-04-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('trending_collection', 'Trending Collection'), ('sold_out', 'Sold out'), ('comingsoon', 'Coming soon'), ('on_sale', 'On Sale'), ('new', 'New'), ('best_seler', 'Best seler')], default='active', max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('trending_products', 'Trending products'), ('sold_out', 'Sold out'), ('comingsoon', 'Coming soon'), ('on_sale', 'On Sale'), ('new', 'New'), ('best_seler', 'Best seler')], default='active', max_length=20, null=True),
        ),
    ]
