# Generated by Django 5.2 on 2025-04-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_collection_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('trending_collections', 'Trending Collections'), ('sold_out', 'Sold out'), ('comingsoon', 'Coming soon'), ('on_sale', 'On Sale'), ('new', 'New'), ('best_seler', 'Best seler')], default='active', max_length=20, null=True),
        ),
    ]
