# Generated by Django 5.2 on 2025-04-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_collection_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='DiscountSubscriber',
        ),
    ]
