# Generated by Django 5.2 on 2025-04-22 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_contact_discountsubscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountSubscriber',
        ),
    ]
