# Generated by Django 5.2 on 2025-04-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_delete_discountsubscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
