# Generated by Django 5.2 on 2025-04-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_collection_slug_remove_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('sold_out', 'Sold out'), ('comingsoon', 'Coming soon'), ('on_sale', 'On Sale'), ('new', 'New'), ('best_seler', 'Best seler')], default='active', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('sold_out', 'Sold out'), ('comingsoon', 'Coming soon'), ('on_sale', 'On Sale'), ('new', 'New'), ('best_seler', 'Best seler')], default='active', max_length=20, null=True),
        ),
    ]
