# Generated by Django 5.2 on 2025-04-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_collection_status_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank if not on sale', max_digits=10, null=True),
        ),
    ]
