# Generated by Django 5.2 on 2025-04-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_product_new_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank if not on sale', max_digits=10, null=True),
        ),
    ]
