# Generated by Django 5.2 on 2025-04-26 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zip_code',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
