# Generated by Django 5.2 on 2025-05-03 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_orderitems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
